### ISSUE TITLE
Question: What are the requirements to be out of beta?

### ISSUE THREAD

**Issue by JustinRyanH** [rust-rspec/rspec#43]
I've used the rspec library for a couple of pet projects currently, and I haven't really found any issue with it. Why are the cargo releases still beta?

**Comment by mackwic** [comment]
Thank you for using Rspec, it's very nice to hear ! :)

Because we want to be able to break the API as we want as it's still in development.

It was a mistake on my part, honestly. I should just have made it a 0.1 and increment from that.

Currently, the API can't  be stabilized because we are still experimenting with formatters, contextes, and how it interacts with the runner. Some of it _could_ be, but I don't have the time nor the experience to untangle the parts.

**Comment by JustinRyanH** [comment]
Thanks for the Reply. I definitely will look into seeing what I can do to contribute to the projejct.

**Comment by regexident** [comment]
This is great! Also apart from actual code contributions be reminded that contributions to the documentation of the code and/or APIs are much appreciated. (Just as are comments à la “this part right here could really use some inline documentation. I have no idea what it’s doing.” of which there will be many, I presume. We want rspec to be as approchable as possible, while providing a rich feature set.)

Oh and something else I’d really, really appreciate is feedback from you (and basically anybody using rspec or considering using it) on the parts of rspec that we did well (and thus should try to not mess with in future refactorings/changes), as well as those parts that don’t quite feel as polished or that you consider outright unusable at the moment. Without feedback we’re at risk of overfitting rspec to our (@mackwic & me) own needs.

**Comment by mackwic** [comment]
as nice as this issue is, I think we can close it.
